### ISSUE TITLE
Feature capture-stream doc is not build on https://docs.rs/pcap/

### ISSUE THREAD

**Issue by Stargateur** [rust-pcap/pcap#205]
It would be better to build with all features in general doc.

```toml
[package.metadata.docs.rs]
all-features = true
```

BTW, we use `docs-rs` features for build.rs when we should probably use env or at least use standard `docsrs` feature https://docs.rs/about/builds#detecting-docsrs
